apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: thepikart/contracts-ufe
  newName: thepikart/contracts-ufe # {"$imagepolicy": "wac-hospital:contracts-ufe:name"}
  newTag: main.20260503.1005 # {"$imagepolicy": "wac-hospital:contracts-ufe:tag"}
