apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: thepikart/contracts-webapi
  newName: thepikart/contracts-webapi # {"$imagepolicy":  "wac-hospital:contracts-webapi:name"}
  newTag: main.20260503.2119 # {"$imagepolicy": "wac-hospital:contracts-webapi:tag"}
- name: thepikart/contracts-ufe
  newName: thepikart/contracts-ufe # {"$imagepolicy": "wac-hospital:contracts-ufe:name"}
  newTag: main.20260503.2250 # {"$imagepolicy": "wac-hospital:contracts-ufe:tag"}
