apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: contracts
    wac-fiit.github.io/project: contracts
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/contracts-ufe
- ../../../apps/contracts-webapi


components:
- ../../../components/version-release